### ISSUE TITLE
Service file permissions

### ISSUE THREAD

**Issue by johanburati** [rfparedes/gdg#3]
I'm seeing the following message in the logs:
```
systemd[1]: Configuration file /etc/systemd/system/gdg.service is marked executable. Please remove executable permission bits. Proceeding anyway.
```

The service filee is created with `755` permissions, I think it should be changed to `644`.
```
-rwxr-xr-x. 1 root root 153 Mar  9 06:47 /etc/systemd/system/gdg.service
```

Btw great project !

**Comment by rfparedes** [comment]
Thanks Johan.  https://github.com/rfparedes/gdg/pull/4
