### ISSUE TITLE
gdg.service: Succeeded. keeps repeating in the logs

### ISSUE THREAD

**Issue by johanburati** [rfparedes/gdg#5]
Hi Rich, 

The `gdg.service: Succeeded.` message keeps repeating in the logs, 
I understand it is related to the interval but that would be nice if we could get rid of that message.

```
Mar  9 07:11:20 r83t systemd[1]: gdg.service: Succeeded.
Mar  9 07:11:50 r83t systemd[1]: gdg.service: Succeeded.
Mar  9 07:12:21 r83t systemd[1]: gdg.service: Succeeded.
Mar  9 07:12:51 r83t systemd[1]: gdg.service: Succeeded.
Mar  9 07:13:22 r83t systemd[1]: gdg.service: Succeeded.
Mar  9 07:13:52 r83t systemd[1]: gdg.service: Succeeded.
Mar  9 07:14:23 r83t systemd[1]: gdg.service: Succeeded.
Mar  9 07:14:53 r83t systemd[1]: gdg.service: Succeeded.
Mar  9 07:15:24 r83t systemd[1]: gdg.service: Succeeded.
Mar  9 07:15:54 r83t systemd[1]: gdg.service: Succeeded.
```

**Comment by rfparedes** [comment]
Hey Johan.  Unfortunately, this cannot be fixed.  The systemd maintainer's stubborn refusal to even consider allowing messages to be filtered from the logs in any way has frustrated many.  His take is that you can filter them with journalctl which I think is not a compromising gesture. I don't agree and would like them never to be written to begin with.
